# Generated by Django 5.2.10 on 2026-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_job_source_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(default=0, help_text='最高月薪(元)'),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(default=0, help_text='最低月薪(元)'),
        ),
    ]
